[pytest]
addopts = -v --html=reports/report.html --self-contained-html
markers =
    smoke: important basic test cases
    regression: full end-to-end test cases
    api: API test cases
    ui: UI test cases
